import configparser
from pathlib import Path
import datetime


def create_obsidian_note(title: str, content: str, tags: list[str] = None):
    """
    Creates a new note in the Obsidian vault specified in the config file.

    Args:
        title: The title of the note. This will also be the filename.
        content: The main content of the note in Markdown format.
        tags: A list of tags to add to the note's frontmatter.
    """
    # 1. Read configuration from config.ini
    config = configparser.ConfigParser()
    config_file = Path(__file__).parent / 'config.ini'

    if not config_file.is_file():
        print(f"Error: Configuration file not found at '{config_file}'")
        _create_default_config(config_file)
        print("A default 'config.ini' has been created. Please edit it with your vault path.")
        return

    config.read(config_file)

    try:
        # Use .expanduser() to handle '~' in the path
        vault_path = Path(config.get('Obsidian', 'vault_path')).expanduser()
        output_folder = config.get('Obsidian', 'output_folder', fallback='.')
    except (configparser.NoSectionError, configparser.NoOptionError) as e:
        print(f"Error in 'config.ini': {e}")
        print("Please ensure 'config.ini' has an [Obsidian] section with a 'vault_path' key.")
        return

    # 2. Prepare file path and name
    # Sanitize title to create a valid filename
    safe_filename = "".join(c for c in title if c.isalnum() or c in (' ', '_', '-')).rstrip()
    output_dir = vault_path / output_folder
    output_file = output_dir / f"{safe_filename}.md"

    # Ensure the output directory exists
    output_dir.mkdir(parents=True, exist_ok=True)

    # 3. Prepare note content with YAML frontmatter (common in Obsidian)
    frontmatter = f"---\n"
    frontmatter += f"title: {title}\n"
    frontmatter += f"date: {datetime.datetime.now().isoformat()}\n"
    if tags:
        frontmatter += f"tags:\n"
        for tag in tags:
            frontmatter += f"  - {tag}\n"
    frontmatter += f"---\n\n"

    full_content = frontmatter + f"# {title}\n\n" + content

    # 4. Write the note to the file
    if output_file.exists():
        print(f"Note '{output_file}' already exists. Skipping creation.")
        return

    try:
        output_file.write_text(full_content, encoding='utf-8')
        print(f"Successfully created note: {output_file}")
    except IOError as e:
        print(f"Error writing to file {output_file}: {e}")


def _create_default_config(config_file: Path):
    """Creates a default config.ini file."""
    config = configparser.ConfigParser()
    config['Obsidian'] = {
        'vault_path': '~/Documents/ObsidianVault',
        'output_folder': 'Notes/Generated'
    }
    try:
        with config_file.open('w') as f:
            config.write(f)
    except IOError as e:
        print(f"Could not create default config file: {e}")


if __name__ == '__main__':
    # --- Example Usage ---
    # You can call create_obsidian_note() with your desired title, content, and tags.

    note_title = "My First Auto-Generated Note"
    note_content = (
        "This is a note generated by a Python script.\n\n"
        "It supports standard Markdown:\n"
        "- Lists\n"
        "- **Bold** and *italic* text\n\n"
        "It can also include Obsidian-style [[wikilinks]] to other notes, like [[Another Note]]."
    )
    note_tags = ["python", "automation", "testing"]

    create_obsidian_note(note_title, note_content, note_tags)